#Necessary to get macvim (gui vim) to have the correct path. Just
#copied from .zshrc.computer.
#
#https://github.com/b4winckler/macvim/wiki/Troubleshooting
#has more information.

#export PATH=$HOME/MacPorts/bin:$PATH
#export PATH=$HOME/MacPort/lib:$PATH
#export PATH=${PATH}:/Users/mcala/soft/fhi98PP/bin/Tools
#export PATH=${PATH}:/Users/mcala/soft/espresso-5.1/bin
