-- ██████╗ ██╗     ██╗███╗   ██╗██╗  ██╗
-- ██╔══██╗██║     ██║████╗  ██║██║ ██╔╝
-- ██████╔╝██║     ██║██╔██╗ ██║█████╔╝
-- ██╔══██╗██║     ██║██║╚██╗██║██╔═██╗
-- ██████╔╝███████╗██║██║ ╚████║██║  ██╗
-- ╚═════╝ ╚══════╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝
-- [Blink](https://github.com/Saghen/blink.cmp)
-- [Docs](https://cmp.saghen.dev/)
-- [Lazyvim](https://www.lazyvim.org/extras/coding/blink)
--
-- As usual, linkarzu has a great set of videos
-- that you followed.
-- https://www.youtube.com/watch?v=sBbplGeFffY
-- https://www.youtube.com/watch?v=JrgfpWap_Pg
-- https://www.youtube.com/watch?v=GxnBIRl9UmA
-- https://www.youtube.com/watch?v=7HYBrw6EDEM
-- https://www.youtube.com/watch?v=FmHhonPjvvA
--
return {
  "saghen/blink.cmp",
  opts = {
    sources = {
      per_filetype = {
        lua = { inherit_defaults = true, "lazydev" },
      },
      providers = {
        lazydev = {
          name = "LazyDev",
          module = "lazydev.integrations.blink",
          score_offset = 100,
        },
      },
    },
  },
}
--

--
--return {
--  "saghen/blink.cmp",
--  enabled = true,
--  dependencies = {
--    "rafamadriz/friendly-snippets",
--    "moyiz/blink-emoji.nvim",
--  },
--  opts = function(_, opts)
--    opts.sources = vim.tbl_deep_extend("force", opts.sources or {}, {
--      default = { "lsp", "path", "snippets", "buffer", "dadbod", "emoji" },
--      providers = {
--        lsp = {
--          name = "lsp",
--          enabled = true,
--          module = "blink.cmp.sources.lsp",
--          kind = "LSP",
--          min_keyword_length = 1,
--          fallbacks = { "snippets", "buffer" },
--          score_offset = 90, -- the higher the number, the higher the priority
--        },
--        path = {
--          name = "Path",
--          module = "blink.cmp.sources.path",
--          score_offset = 25,
--          fallbacks = { "snippets", "buffer" },
--          min_keyword_length = 2,
--          opts = {
--            trailing_slash = false,
--            label_trailing_slash = true,
--            get_cwd = function(context)
--              return vim.fn.expand(("#%d:p:h"):format(context.bufnr))
--            end,
--            show_hidden_files_by_default = true,
--          },
--        },
--        buffer = {
--          name = "Buffer",
--          enabled = true,
--          max_items = 3,
--          module = "blink.cmp.sources.buffer",
--          min_keyword_length = 2,
--          score_offset = 15,
--        },
--        snippets = {
--          name = "snippets",
--          enabled = true,
--          max_items = 15,
--          min_keyword_length = 2,
--          module = "blink.cmp.sources.snippets",
--          score_offset = 85, -- the higher the number, the higher the priority
--          -- Only show snippets if I type the trigger_text characters, so
--          -- to expand the "bash" snippet, if the trigger_text is ";" I have to
--          should_show_items = function()
--            local col = vim.api.nvim_win_get_cursor(0)[2]
--            local before_cursor = vim.api.nvim_get_current_line():sub(1, col)
--            -- NOTE: remember that `trigger_text` is modified at the top of the file
--            return before_cursor:match(trigger_text .. "%w*$") ~= nil
--          end,
--          -- After accepting the completion, delete the trigger_text characters
--          -- from the final inserted text
--          -- Modified transform_items function based on suggestion by `synic` so
--          -- that the luasnip source is not reloaded after each transformation
--          -- https://github.com/linkarzu/dotfiles-latest/discussions/7#discussion-7849902
--          -- NOTE: I also tried to add the ";" prefix to all of the snippets loaded from
--          -- friendly-snippets in the luasnip.lua file, but I was unable to do
--          -- so, so I still have to use the transform_items here
--          -- This removes the ";" only for the friendly-snippets snippets
--          transform_items = function(_, items)
--            local line = vim.api.nvim_get_current_line()
--            local col = vim.api.nvim_win_get_cursor(0)[2]
--            local before_cursor = line:sub(1, col)
--            local start_pos, end_pos = before_cursor:find(trigger_text .. "[^" .. trigger_text .. "]*$")
--            if start_pos then
--              for _, item in ipairs(items) do
--                if not item.trigger_text_modified then
--                  ---@diagnostic disable-next-line: inject-field
--                  item.trigger_text_modified = true
--                  item.textEdit = {
--                    newText = item.insertText or item.label,
--                    range = {
--                      start = { line = vim.fn.line(".") - 1, character = start_pos - 1 },
--                      ["end"] = { line = vim.fn.line(".") - 1, character = end_pos },
--                    },
--                  }
--                end
--              end
--            end
--            return items
--          end,
--        },
--        -- Example on how to configure dadbod found in the main repo
--        -- https://github.com/kristijanhusak/vim-dadbod-completion
--        dadbod = {
--          name = "Dadbod",
--          module = "vim_dadbod_completion.blink",
--          min_keyword_length = 2,
--          score_offset = 85,
--        },
--        -- https://github.com/moyiz/blink-emoji.nvim
--        emoji = {
--          module = "blink-emoji",
--          name = "Emoji",
--          score_offset = 93,
--          min_keyword_length = 1,
--          opts = { insert = true }, -- Insert emoji (default) or complete its name
--        },
--      },
--    })
--    opts.completion = {
--      trigger = {
--        show_on_trigger_character = true,
--      },
--      list = { max_items = 500 },
--      menu = {
--        border = "single",
--      },
--      documentation = {
--        auto_show = true,
--        window = {
--          border = "single",
--        },
--      },
--    }
--    opts.snippets = {
--      preset = "luasnip", -- Choose LuaSnip as the snippet engine
--    }
--    opts.keymap = {
--      preset = "default",
--      ["<Tab>"] = { "snippet_forward", "fallback" },
--      ["<S-Tab>"] = { "snippet_backward", "fallback" },
--
--      ["<Up>"] = { "select_prev", "fallback" },
--      ["<Down>"] = { "select_next", "fallback" },
--      ["<C-p>"] = { "select_prev", "fallback" },
--      ["<C-n>"] = { "select_next", "fallback" },
--
--      ["<S-k>"] = { "scroll_documentation_up", "fallback" },
--      ["<S-j>"] = { "scroll_documentation_down", "fallback" },
--
--      ["<C-space>"] = { "show", "show_documentation", "hide_documentation" },
--      ["<C-e>"] = { "hide", "fallback" },
--    }
--    return opts
--  end,
--}
