#: schema https://raw.githubusercontent.com/rvben/rumdl/main/rumdl.schema.json
# ██████╗ ██╗   ██╗███╗   ███╗██████╗ ██╗     
# ██╔══██╗██║   ██║████╗ ████║██╔══██╗██║     
# ██████╔╝██║   ██║██╔████╔██║██║  ██║██║     
# ██╔══██╗██║   ██║██║╚██╔╝██║██║  ██║██║     
# ██║  ██║╚██████╔╝██║ ╚═╝ ██║██████╔╝███████╗
# ╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝╚═════╝ ╚══════╝
#
# A high-performance Markdown linter and formatter, written in Rust
# [Link to GH](https://github.com/rvben/rumdl)
# [Link to Rules](https://rumdl.dev/)


line-length = 90
exclude = ["node_modules", "build", "dist"]
respect-gitignore = true
flavor = "gfm"


[MD004]
indent = 2

[MD013]
reflow = true
code-blocks = false
tables = false
