#!/bin/bash
# md2tufte: Convert one or more Markdown files to a Tufte-style research-paper
# PDF, with sidenotes in the margin instead of footnotes at the foot.
#
# Usage:
#   md2tufte.sh <input.md> [input2.md ...] [-o output.pdf]
#
# When multiple inputs are given they are concatenated into a single source:
# the first file is kept verbatim (its YAML frontmatter drives title, author,
# abstract, bibliography, CSL). Subsequent files have any leading YAML
# frontmatter stripped and are prefixed with `\newpage` so each starts on a
# fresh page.
#
# Uses pandoc + xelatex + the tufte-handout class + the header.tex in
# ../assets/. See SKILL.md for YAML frontmatter conventions, the sidenote
# float caveat, and Tufte-specific features (margin notes/figures, full-width
# blocks, \newthought).

set -euo pipefail

usage() {
  echo "Usage: $(basename "$0") <input.md> [input2.md ...] [-o output.pdf]" >&2
  exit 2
}

OUTPUT=""
INPUTS=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    -o|--output)
      [[ $# -lt 2 ]] && usage
      OUTPUT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    --)
      shift
      while [[ $# -gt 0 ]]; do INPUTS+=("$1"); shift; done
      ;;
    -*)
      echo "Unknown flag: $1" >&2
      usage
      ;;
    *)
      INPUTS+=("$1")
      shift
      ;;
  esac
done

[[ ${#INPUTS[@]} -lt 1 ]] && usage

for f in "${INPUTS[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "Input not found: $f" >&2
    exit 1
  fi
done

if [[ -z "$OUTPUT" ]]; then
  OUTPUT="${INPUTS[0]%.md}.pdf"
fi

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HEADER="$SKILL_DIR/assets/header.tex"

if [[ ! -f "$HEADER" ]]; then
  echo "Missing asset: $HEADER" >&2
  exit 1
fi

TMP="$(mktemp "${TMPDIR:-/tmp}/md2tufte.XXXXXX")"
trap 'rm -f "$TMP"' EXIT

# First file: keep as-is (frontmatter drives document metadata).
cat "${INPUTS[0]}" > "$TMP"

# Subsequent files: strip leading YAML frontmatter block (if any) and prepend
# a page break so each file starts on a new page.
for ((i=1; i<${#INPUTS[@]}; i++)); do
  printf '\n\\newpage\n\n' >> "$TMP"
  awk '
    BEGIN { in_yaml = 0; past_yaml = 0 }
    NR == 1 && /^---[[:space:]]*$/ { in_yaml = 1; next }
    in_yaml && /^(---|\.\.\.)[[:space:]]*$/ { in_yaml = 0; past_yaml = 1; next }
    in_yaml { next }
    { past_yaml = 1; print }
  ' "${INPUTS[i]}" >> "$TMP"
done

# Disclaimer footnote: forced on every build. Pandoc wires the `thanks`
# metadata into \title{...\thanks{...}}; tufte-handout renders that title note
# in the margin, so the disclaimer shows up as a sidenote on the first page.
# Passed via -M so it always overrides any `thanks` set in the source.
# Kept pure ASCII on purpose: this string is passed via argv (-M), and under a
# non-UTF-8 locale pandoc would mangle a literal em dash into U+FFFD. ASCII is
# robust everywhere.
DISCLAIMER="This report was generated by an AI system (Claude) under human direction. AI can make mistakes and may fabricate facts, figures, or citations, so verify independently before relying on it."
META=(-M "thanks=$DISCLAIMER")

# Author comes from the first file's frontmatter — see SKILL.md for the
# required "Claude (MODEL) under direction of Andrew McAllister" format, where
# the authoring model fills in MODEL. The script can't know which model is
# running, so when the frontmatter omits an author entirely it falls back to a
# model-less byline rather than leaving it blank.
if ! awk '
    NR == 1 && /^---[[:space:]]*$/ { in_yaml = 1; next }
    in_yaml && /^(---|\.\.\.)[[:space:]]*$/ { in_yaml = 0; next }
    in_yaml && /^author[[:space:]]*:/ { found = 1 }
    END { exit (found ? 0 : 1) }
  ' "${INPUTS[0]}"; then
  META+=(-M "author=Claude under direction of Andrew McAllister")
fi

# Body font. The tufte-handout class defaults to plain Latin Modern under
# xelatex; the classic Tufte look wants Palatino (Bembo in the originals).
# Default to TeX Gyre Pagella (the free Palatino, ships with every TeX Live)
# ONLY when the frontmatter does not set its own mainfont — a command-line -V
# would override frontmatter, so detect-then-inject keeps the user in control.
if ! awk '
    NR == 1 && /^---[[:space:]]*$/ { in_yaml = 1; next }
    in_yaml && /^(---|\.\.\.)[[:space:]]*$/ { in_yaml = 0; next }
    in_yaml && /^mainfont[[:space:]]*:/ { found = 1 }
    END { exit (found ? 0 : 1) }
  ' "${INPUTS[0]}"; then
  META+=(-V "mainfont=TeX Gyre Pagella")
fi

# NOTE: no -V geometry — tufte-handout owns the page layout (the wide right
# margin is where sidenotes live). Passing geometry causes an option clash.
pandoc "$TMP" \
  -f markdown \
  --pdf-engine=xelatex \
  -V documentclass=tufte-handout \
  -V colorlinks=true \
  "${META[@]}" \
  --include-in-header="$HEADER" \
  --citeproc \
  --highlight-style=tango \
  -o "$OUTPUT"

echo "Created: $OUTPUT"
