#!/bin/bash
# This is fixbb version 0.31.  Copyright 2000 by Jeff Spirko.
# Redistributable under the GNU General Public License.
# See http://topquark.dhs.org/~spirko/fixbb/

# Changes by Petr Mikulik:
#   -  8.  9. 2000: working file in the $TMP directory; remove backup file
#   - 18. 10. 2000: AWKPARSEBB to support multiple-page (non-EPS) documents
#   - 26. 10. 2000: error if bounding box not determined (GS < 5.50 or empty
#     pages); page status info added

# Options for ghostscript to print the BoundingBox without other junk.
GSOPTS="-dQUIET -dBATCH -dNOPAUSE -sDEVICE=bbox"
export GSOPTS

AWKPROG='
	(found) { print; next }
	$1 == "%%BoundingBox:" { print $1, ENVIRON["bbox"]; found=1; next }
	{ print }
	'

# Finds min and max of the 4 numbers after the "%%BoundingBox:" label
AWKPARSEBB='
	BEGIN { x1=99999; y1=99999; x2=0; y2=0; page=0 }
	$1!= "%%BoundingBox:" { next }
	$2<0 || $3<0 { next }
	x1>$2 { x1=$2 }
	y1>$3 { y1=$3 }
	x2<$4 { x2=$4 }
	y2<$5 { y2=$5 }
	{ page++; printf "Page " page ": " $0 "  max = " x1 " " y1 " " x2 " " y2  "  \t\r" >"/dev/stderr" }
	END { printf "\t\t\t\t\t\t\t\r" >"/dev/stderr"
	      print x1 " " y1 " " x2 " " y2 }
	'
function correctingBB {
    # find bounding box
    BBOX=`grep %%BoundingBox: $FILE`; 
    # tokenize the bounding box string
    ARR=(${BBOX});
    echo 'Found bounding box:           ' $BBOX;
    # echo result
    echo 'Found the offending boundary: ' $BADBOUND;
    # replace the undesired boundary with 0
    BBOXNEW=${BBOX/$BADBOUND/0};
    # determine the value that this bound should have
    NEWBOUND=$(($ADJBOUND - $BADBOUND));
    # replace the adjusted bound with the new value
    BBOXNEW=${BBOXNEW/$ADJBOUND/$NEWBOUND};
    # echo
    echo 'Correct bounding box:         ' $BBOXNEW;
    echo 'Translating by adding:        ' $TRANSLATE;
    echo '';   
    # replace the old bounding box line with the new one
    sed -i "s/$BBOX/$BBOXNEW/" $FILE;
    # translate the image
    sed -i "s/%%EndComments/%%EndComments\n\n$TRANSLATE/" $FILE;}

export bbox

######################################################################
######################################################################
# START PROGRAM
######################################################################
######################################################################
# Each command-line argument is assumed to be a file to process
for FILE in $* ; do

### MODIFICATION Konstantin Weber -- 2012/20/01
######################################################################
## CHECK FOR NEGATIVE BOUNDING BOX
# find bounding Box
BBOX=`grep %%BoundingBox: $FILE`; 
# tokenize the bounding box string
ARR=(${BBOX});

if [[ -e $FILE && ( $(grep -c %%BoundingBox: $FILE) == 1) ]]; then
    if [[ ${ARR[1]} < 0 || ${ARR[2]} < 0 ]]; then
	if [[ ${ARR[1]} < 0 ]]; then
	    BADBOUND=${ARR[1]};
            ADJBOUND=${ARR[3]};
            # generate additional line to translate image
	    TRANSLATE=`echo ${BADBOUND:1} 0 ' translate'`;
	    correctingBB;
	fi
	if [[ ${ARR[2]} < 0 ]]; then
	    BADBOUND=${ARR[2]};
            ADJBOUND=${ARR[4]};
            # generate additional line to translate image
	    TRANSLATE=`echo 0 ${BADBOUND:1} ' translate'`;
	    correctingBB;
	fi
    fi
fi
echo 'Done checking for wrong Bounding Boxes';
######################################################################

#  BAK=${FILE}~
#  if [ "$TMP" = "" ]; then TMP="."; fi; BAK=$TMP\fixbb__.ps
  BAK='fixbb$$.ps'

  # Get the correct BoundingBox from ghostscript.
  # Old: bbox=`gs ${GSOPTS} ${FILE} 2>&1 | gsort | head -1 | cut -d\  -f 2-`
  bbox=`/usr/bin/gs ${GSOPTS} ${FILE} 2>&1 | awk "$AWKPARSEBB"`

  case $bbox in
    "99999 99999 0 0")
	echo "Bounding box was NOT determined (empty pages or Ghostscript >= 5.50 required)"
	#exit ;;
  esac

  echo "Bounding box for \""$FILE"\" is: "$bbox

  # Save the old version of the file
  mv $FILE $BAK

  # Create the new version, replacing the old BoundingBox
  awk "$AWKPROG" $BAK > $FILE

  case `uname` in 
    "OS/2") dos2unix $FILE ;;
  esac

  # delete the backup file
  rm -f $BAK
  
### MODIFICATION Konstantin Weber -- 2012/20/01
######################################################################
## CREATE PDF
  if [[ $file == *.eps ]]; then
      FILEPDF=${$FILE//.eps/.pdf}      
  elif [[ $file == *.ps ]]; then
      FILEPDF=${$FILE//.ps/.pdf}      
  fi
  
  ps2pdf -dEPSCrop $FILE $FILEPDF
######################################################################  

done
