
[[session]]
name = "Research"
path = "/Users/mcala/Developer/1_active/research" 

[[session]]
name = "NJ Legislature"
path = "/Users/mcala/Developer/1_active/nj_legislature" 

[[session]]
name = "Research Old"
path = "/Users/mcala/Developer/1_active/research-old" 

[[session]]
name = "SFRA Data Process"
path = "/Users/mcala/Developer/1_active/sfra_data_process" 