# ZSH Environment for sonmi-451
# Author: Andrew McAllister (andrew@mcallister.science)

# -- Fallback for $HOME
export HOME=${HOME:-/Users/mcala}

## XDG Specification
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_STATE_HOME=$HOME/.local/state
export XDG_DATA_HOME=$HOME/.local/share

## MacPorts
export MACPORTS_PREFIX=/Users/mcala/MacPorts
# export DYLD_FALLBACK_LIBRARY_PATH=/Users/mcala/MacPorts/lib

## Application Configuration
export ZIM_HOME=$XDG_CONFIG_HOME/zim
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export RCRC=$XDG_CONFIG_HOME/rcm/rcrc
export EZA_CONFIG_DIR=$XDG_CONFIG_HOME/eza
export LLM_USER_PATH=$XDG_CONFIG_HOME/llm
[[ -f "$HOME/.bun" ]] && export BUN_INSTALL="$HOME/.bun"

## Neovim & Editors
export EDITOR=nvim
export VISUAL=$EDITOR
export NVIM_APPNAME=nvim-lazy
export GIT_EDITOR=nvim

## Pagers
export PAGER=less
export BAT_PAGER=less

## Manual Pages
export MANPATH=$MANPATH:$HOME/software/man
export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat -p -lman'"
export MANWIDTH=80

## One Password CLI
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock


# -- Functions
FPATH=$XDG_CONFIG_HOME/zfunc:$XDG_CONFIG_HOME/zsh_functions:${FPATH}
autoload -Uz calc checksha find_empty_dirs path rename_files gpg-cache

[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

echo "PATH after zshenv: $PATH" >> ~/path_debug.log
