# ZSH Environment for sonmi-451
# Author: Andrew McAllister (andrew@mcallister.science)

# --- Exports
## Configuration Files
export XDG_CONFIG_DIR=/Users/mcala/.config
export XDG_CONFIG_HOME=$XDG_CONFIG_DIR
export XDG_CACHE_DIR=/Users/mcala/.cache
export MACPORTS_PREFIX=/Users/mcala/MacPorts
export RCRC=$XDG_CONFIG_DIR/rcm/rcrc
export ZDOTDIR=$XDG_CONFIG_DIR/zsh
export ZIM_HOME=$XDG_CONFIG_DIR/zim

## Perl, which is only used for exiftools
export PERL5LIB=$MACPORTS_PREFIX/lib/perl5/vendor_perl/5.34

## Editors
export NVIM_APPNAME=nvim-lazy
export EDITOR=nvim
export GIT_EDITOR=nvim

## Manual Pages
export MANPATH=$MANPATH:$HOME/software/man
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export MANWIDTH=80

# --- Path
export PATH=$HOME/software/bin:$PATH
export PATH=$HOME/software/lib:$PATH
export PATH=$HOME/software/share:$PATH
export PATH=$HOME/MacPorts/bin:$PATH
export PATH=$HOME/MacPorts/sbin:$PATH
export PATH=$HOME/MacPorts/lib:$PATH
export PATH=$HOME/MacPorts/lib/ImageMagick7/bin:$PATH
export PATH=$HOME/opt/bin:$PATH
export PATH=$HOME/opt/lib:$PATH
export PATH=/Library/TeX/texbin/:$PATH
export PATH=/Users/mcala/.local/bin:$PATH

## Exclusively for tmuxinator...
export PATH=/Users/mcala/.rbenv/versions/3.3.6/bin:$PATH

# -- Functions
FPATH=${FPATH}:${XDG_CONFIG_DIR}/zsh_functions
autoload calc.zsh rename_files.zsh path.bash checksha.zsh

# Other Environments
source "$HOME/.cargo/env"
