# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/mcala/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/mcala/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/mcala/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/mcala/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source $HOME/.zshrc.personal
#source $HOME/.zshrc.prompt
source $HOME/.zshrc.computer


#
## Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
#export PATH="$PATH:$HOME/.rvm/bin"
#
#OLD OHMYZSH CONFIG
## Path to your oh-my-zsh configuration.
#ZSH=$HOME/soft/repositories/oh-my-zsh
#
## Uncomment following line if you want to disable autosetting terminal title.
#DISABLE_AUTO_TITLE="true"
#ENABLE_CORRECTION="true"
#HIST_STAMPS="mm/dd/yyyy"
##ZSH_CUSTOM=$HOME/.zsh_plugins
#
##plugins for oh-my-zsh
##source $HOME/.plugins.zsh
##plugins+=(git colored-man-pages zsh-syntax-highlighting)
#
## Load personal and computer specific preferences
#source $ZSH/oh-my-zsh.sh
#source $HOME/.zshrc.personal
#source $HOME/.zshrc.prompt
#source $HOME/.zshrc.computer
#source ~/.iterm2_shell_integration.`basename $SHELL`


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
